name: riverable
description: "An example integration of Riverpod and flutter_reactive_ble."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  lint_staged: ^0.5.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart format --fix
