name: riverable
description: "An example integration of Riverpod and flutter_reactive_ble."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  easy_debounce: ^2.0.3
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_reactive_ble: ^5.3.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.8.1
  permission_handler: ^11.3.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  husky: ^0.1.7
  json_serializable: ^6.7.1
  lint_staged: ^0.5.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart format --fix
