name: riverable
description: "An example integration of Riverpod and flutter_reactive_ble."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart format --fix
